### ISSUE TITLE
Update text area styling

### ISSUE THREAD

**Issue by davetaz** [theodi/interactive-data-ethics-canvas#30]
I like the look of the following style for the textareas. Note that the font-size may need to cascasde to be a global change.

    width: 95%;
    font-size: 1.3em;
    box-sizing: border-box;
    border: none;
    resize: none;
    margin-left: auto;
    margin-right: auto;
    line-height: 1.2em;
    padding: 0.5em;
    color: #444;

**Comment by davetaz** [comment]
Text area should be in center of parent between dots at 95% width

**Comment by gilesdring** [comment]
Is this the same for all text elements, or just textareas?

**Comment by davetaz** [comment]
All text inputs, be it short, long or other.

**Comment by gilesdring** [comment]
This is quite an involved change, given the desire to align list and text content - Will require some tinkering to get right given all combinations of elements (and it's a change to each element, given how the spacing / labels work). I will look at this once the data load work is underway.

**Comment by davetaz** [comment]
It looks fine to me with my changes. So hopefully shouldn't be too hard to apply on the div that contains the input components?

![image](https://user-images.githubusercontent.com/180099/111345143-e7e7f980-8674-11eb-9837-2129b630a17b.png)

Understand you point about it applying to different elements in different ways. Sure you'll find an intelligent way to do it.
