### ISSUE TITLE
Control panel (when under - read after HD)

### ISSUE THREAD

**Issue by davetaz** [theodi/interactive-data-ethics-canvas#34]
Again there is a preview in the weekly notes

https://docs.google.com/document/d/1r-jaS7WV4lHnZYhR7J9jis8oxkpoQJNPlC7o_gKAwU8/edit?usp=sharing 

1. Get rid of col-span's, they don't work
2. Background colour same as canvas
3. Stack the filters (status above group, same when in HD).

**aside:**
    background: #eee;
    top: -2px; // FIX SO THIS ISN'T NEEDED
    border-top: 1px dashed #777;
    padding-left: 1em;
    padding-right: 1em;
    padding-bottom: 10px;

**buttons div:**
    border-right: 1px dashed #777;
    padding-right: 1em;
    padding-top: 10px;
    min-width: 200px; //OR MAKE IT SO THEY CAN'T SHRINK MORE THAN THE WIDTH OF A DOTTED SQUARE IN THE BUBBLES ON THE CANVAS

The filters style is not right in the screen shot. There should be a dashed line between them, but the dashed line should be 10px longer than the content, so padding is needed. 

Paragraph section on the right is same as HD and takes up the remaining space. What goes in here should be configurable.

**Comment by gilesdring** [comment]
@davetaz I think I've fixed the col span issue, so we have a 5-column grid again. I'll push and let you take a look - I've not yet fixed the spacing on the dotted lines (as I missed the comment while working on them). I assume from comments here that these should join up at all points, rather than have edge?

**Comment by davetaz** [comment]
Note that the status bar should be the same width as canvas+aside, not full screen with. If the aside in underneath then the stutus bar should be the same width as the canvas. This keeps it all contained in a rectangle. 

On the dots, they almost connect but not quiet. Take a look at my live version to get the idea. 

https://davetaz.github.io/idec/idec-basic/index.html

The important thing is that the content (buttons, filters, text etc) has padding so that the dots extend 10px beyond the content towards the other borders. 

I have to say I'm not a fan of the 5 column layout when the aside is below and the filters take up too much space I think limit this until it is very similar to the version I have in the doc (again this shows the padding on the dots.) 

https://docs.google.com/document/d/1r-jaS7WV4lHnZYhR7J9jis8oxkpoQJNPlC7o_gKAwU8/edit#heading=h.62642b49d6qa

**Comment by davetaz** [comment]
Also note that my dots are not the blue. I tried it and a dark grey looks way better. #777

**Comment by gilesdring** [comment]
[ ] limit width of button to 245px when in narrow mode
