### ISSUE TITLE
Add title naming to canvas

### ISSUE THREAD

**Issue by gilesdring** [theodi/interactive-data-ethics-canvas#41]

**Comment by davetaz** [comment]
Hi Giles, Can it be that people rename the canvas to replace the main title please. 

See example here:

https://davetaz.github.io/idec/idec-basic/new-load.html

**Comment by davetaz** [comment]
I really like the behaviour with the input field not being a placeholder as again the browser behaviour is aweful, so can it not be a placeholder please?

In terms of UX, I was thinking when people press "New" they are prompted to enter a name or can enter it also on the card that goes in the list on the list of canvas screens.

![image](https://user-images.githubusercontent.com/180099/111352435-12898080-867c-11eb-8777-2ac192f1a362.png)
