### ISSUE TITLE
Add actions & decisions as tab in guidance area for every blob

### ISSUE THREAD

**Issue by gilesdring** [theodi/interactive-data-ethics-canvas#44]
* Let's model decisions as actions with no priority
* Toggle between adding d or a
* Filter visible actions / added actions in bubble to that section

- [x] Add actions pane to all editors
- [x] Update actions model to cover decisions as well
- [x] Update actions model to capture associated area for action/decision
- [x] Filter actions displayed on the actions editor
- [ ] Sort items as high, decisions, medium, low

**Comment by gilesdring** [comment]
Leave this to the 'print view'

**Comment by davetaz** [comment]
Looking good. A bit of style for the buttons:

width: 48%;
background: white;
color: var(--know); (OR WHATEVER THE PRIMARY COLOUR OF THE SECTION IS)
