### ISSUE TITLE
Alerting for need to save / your responsiblity to manage data

### ISSUE THREAD

**Issue by gilesdring** [theodi/interactive-data-ethics-canvas#58]
When not detected if user has accepted responsilibity (stored in localStorage)

Present info. Allow user to say 'don't show this again'.

1. first time you load it! Welcome + Warning
2. first time you close it! Warning

Each is a separate accepted setting.

**Comment by davetaz** [comment]
Welcome + Warning

![image](https://user-images.githubusercontent.com/180099/112647543-8d068d00-8e40-11eb-8495-6407a9cf6558.png)

See https://davetaz.github.io/idec/idec-basic/index.html

Message 

Welcome

The ODI Data Ethics Canvas is a tool for anyone who collects, shares or uses data. It helps identify and manage ethical issues – at the start of a project that uses data, and throughout.

Click on each bubble to:

Complete specific questions related to each area.
Access further guidance on each area as well as discover links to additional resources and learning related to each area.
Create actions and note decisions. The "Your Actions" bubble collates all actions/decisions and allows you to add additional ones.
Set a status for each area.

Saving your work
Please note that all progress is saved locally in your browser (no data ever leaves your computer). If you are in private browsing mode then once you close the tab all progress will be lost. The same is true if you clear your browsing history.

To save your progress you can:

Download each canvas using the button in the control panel
Click the download ( ) or share ( ) icons against each canvas in the New / Load area.

**Comment by davetaz** [comment]
Note that the screenshots will need updating once we have a final canvas.

**Comment by davetaz** [comment]
WARNING on close message:

Are you sure you want to leave this page? You should consider downloading a backup of your work before leaving as progress will be lost if you are in private browsing mode or if you clear your web browsing history.

**Comment by gilesdring** [comment]
I've put in an initial version of the 'welcome' page, which is has slightly different controls than the mocked up version. I think making the 'Accept and close' message clear on the button shows intent a bit more. I also decided against using a filled in data sources form, as this may be undesirable to include 'real organisational data' in a help image.

**Comment by gilesdring** [comment]
> WARNING on close message:
> 
> Are you sure you want to leave this page? You should consider downloading a backup of your work before leaving as progress will be lost if you are in private browsing mode or if you clear your web browsing history.

@davetaz We may not be able to include all this text. Support for this appears inconsistent across browsers.

See https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event for more details.

**Comment by davetaz** [comment]
I think this is fine as it is now. Happy to close

**Comment by gilesdring** [comment]
Resolved for now - maybe add to backlog in case there is a more elegant solution?
